### ISSUE TITLE
Error with channel_id

### ISSUE THREAD

**Issue by fmhall** [101dotxyz/GPTeam#34]
```
Traceback (most recent call last):
  File "/Users/mhall/personal/GPTeam/src/main.py", line 37, in run_world
    world = await World.from_id(worlds[-1]["id"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhall/personal/GPTeam/src/world/base.py", line 72, in from_id
    locations = [Location(**location) for location in locations]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhall/personal/GPTeam/src/world/base.py", line 72, in <listcomp>
    locations = [Location(**location) for location in locations]
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhall/personal/GPTeam/src/location/base.py", line 50, in __init__
    super().__init__(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Location
channel_id
  value is not a valid integer (type=type_error.integer)
```

When using my OpenAI key and nothing else.

Python 3.11.

Channel IDs should be Optional, but for some reason Pydantic thinks int is required

**Comment by Alec2435** [comment]
Having trouble replicating this exact error. Did this happen right after launching or was this later in the run? Also was this right after resetting/seeding the database (done automatically if you run `setup.py`) or a non-fresh db?

**Comment by Alec2435** [comment]
Just pushed a fix for this to main
