### ISSUE TITLE
Discord bots are offline, parsing errors

### ISSUE THREAD

**Issue by elliptic1** [101dotxyz/GPTeam#36]
I've set up the Discord server. When I run the world, I see some activity, movement between rooms, and once or twice a message was posted, but all the bots statuses remain offline.

Then soon I get some parsing errors and everything stops.

```
[Calvin] Moved Location Break Room -> Conference Room @ 05:05:45
[Rebecca] Observed 0 new events Last checked events at 04:59:08
[Ricardo] Observed 0 new events Last checked events at 04:50:53
[Jacquelin] Observed 0 new events Last checked events at 04:35:58
Traceback (most recent call last):
  File "/Users/toddsmith/.virtualenvs/GPTeam/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 25, in parse
    json_object = json.loads(json_str)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toddsmith/PycharmProjects/GPTeam/src/main.py", line 45, in run_world
    await world.run()
  File "/Users/toddsmith/PycharmProjects/GPTeam/src/world/base.py", line 113, in run
    await asyncio.gather(*tasks)
  File "/Users/toddsmith/PycharmProjects/GPTeam/src/world/base.py", line 101, in run_agent_loop
    await self.run_next_agent()
  File "/Users/toddsmith/PycharmProjects/GPTeam/src/world/base.py", line 96, in run_next_agent
    await agent.run_for_one_step()
  File "/Users/toddsmith/PycharmProjects/GPTeam/src/agent/base.py", line 1135, in run_for_one_step
    self.react_response = await self._react(events)
  File "/Users/toddsmith/PycharmProjects/GPTeam/src/agent/base.py", line 910, in _react
    parsed_reaction_response: LLMReactionResponse = reaction_parser.parse(response)
  File "/Users/toddsmith/.virtualenvs/GPTeam/lib/python3.10/site-packages/langchain/output_parsers/fix.py", line 38, in parse
    parsed_completion = self.parser.parse(new_completion)
  File "/Users/toddsmith/.virtualenvs/GPTeam/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 31, in parse
    raise OutputParserException(msg)
langchain.schema.OutputParserException: Failed to parse LLMReactionResponse from completion postpone

```

**Comment by Alec2435** [comment]
This seems unrelated to discord and is just a general parsing error. This tends to happen when the model returns a response we can't parse. Especially common on `gpt-3.5-turbo`. We're working on trying to improve this but PRs are appreciated!
