### ISSUE TITLE
Failing to setup

### ISSUE THREAD

**Issue by nigelp** [101dotxyz/GPTeam#42]
Hi, Can someone help please? I'm trying to install on Windows 10. Getting this error after 'poetry run world'

D:\GPTeam>poetry run world
Traceback (most recent call last):
  File "D:\GPTeam\src\main.py", line 35, in run_world
    raise ValueError("No worlds found!")
ValueError: No worlds found!

When I try to do a database reset I get this:

D:\GPTeam>poetry run db-reset
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\GPTeam\src\utils\database\reset.py", line 28, in main
    asyncio.run(reset())
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\GPTeam\src\utils\database\reset.py", line 19, in reset
    subprocess.run(["del", "-f", "database.db"])
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by joshsny** [comment]
@nigelp  Looks like your setup script for the database never seeded correctly.

That reset error is occurring due to an error in `db-reset` on Windows. I have just pushed a fix for that, so can you re-run `poetry run db-reset` and paste the output here?

**Comment by joshsny** [comment]
```
File "D:\GPTeam\src\utils\database\reset.py", line 19, in reset
subprocess.run(["del", "-f", "database.db"])
```

That's odd, this line is no longer in the `main` branch of the repo so that error should not be occurring if you are running the latest changes (and I can see you ran `git pull` 🤔).

Can you re-clone the repo from scratch just to make sure there isn't an issue with pulling the right changes?

**Comment by nigelp** [comment]
@joshsny that did it - eventually. It seemed to repeat the problem the first time, but after I updated the .env it went smoothly. Thanks for your help, it's wacky! :)
