### ISSUE TITLE
'poetry: command not found' after successful setup

### ISSUE THREAD

**Issue by TradingPlacesResearch** [101dotxyz/GPTeam#44]
1. Cloned repository to my user folder on M1 Mac.
2. Navigated to the new directory `~/gpteam`
3. Ran `setup.py`. Installs poetry with no errors.
4. Put my API key into `.env`
5. `poetry run world` returns `command not found`

```
(base) Mac-Studio-6:~ USERNAME$ cd ~/gpteam
(base) Mac-Studio-6:gpteam USERNAME$ python setup.py
⚠️ Poetry not found. Would you like to install it now? (y/n): y
Installing Poetry…
Retrieving Poetry metadata

The latest version (1.4.2) is already installed.
Installing dependencies…
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: 101-ai (0.1.0)
Seed the database…
database reset
seeding the db - normal

Setup complete!

-> You are ready to run the world. Please set your OPENAI_API_KEY in .env and run `poetry run world` to get started.
(base) Mac-Studio-6:gpteam USERNAME$ poetry run world
-bash: poetry: command not found
```
Python 3.10.6

Thanks!

**Comment by joshsny** [comment]
@TradingPlacesResearch Can you try re-run in another terminal and see if poetry is installed?

**Comment by TradingPlacesResearch** [comment]
Did that. Same sequence as quoted in OP. Then switched to the new Mac shell, zsh, to see if that makes a difference. Same sequence

```
USERNAME@Mac-Studio-6 gpteam % python3 setup.py
⚠️ Poetry not found. Would you like to install it now? (y/n): y
Installing Poetry...
Retrieving Poetry metadata

The latest version (1.4.2) is already installed.
Installing dependencies...
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: 101-ai (0.1.0)
Seed the database...
database reset
seeding the db - normal

Setup complete!

-> You are ready to run the world. Please set your OPENAI_API_KEY in .env and run `poetry run world` to get started.
USERNAME@Mac-Studio-6 gpteam % poetry run world
zsh: command not found: poetry
```

**Comment by philip-pentatonic** [comment]
Try running it in a venv, that worked for me. You have to close the terminal and restart it when you're done to refresh it though.

`python3 -m venv venv`
`source venv/bin/activate`

Then, I reran 

`python3 setup.py`

Then closed down Terminal and reopened it. Made sure I was still in (venv) and ran:

`poetry run world`

Let us know if that works

**Comment by TradingPlacesResearch** [comment]
Error in setup:

```
USERNAME@Mac-Studio-6 ~ % cd ~/gpteam
USERNAME@Mac-Studio-6 gpteam % python3 -m venv venv
USERNAME@Mac-Studio-6 gpteam % source venv/bin/activate
(venv) USERNAME@Mac-Studio-6 gpteam % python3 setup.py
⚠️ Poetry not found. Would you like to install it now? (y/n): y
Installing Poetry...
Retrieving Poetry metadata

The latest version (1.4.2) is already installed.
Installing dependencies...
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: 101-ai (0.1.0)
Seed the database...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/USERNAME/gpteam/src/utils/database/reset.py", line 8, in <module>
    from .seed import seed
  File "/Users/USERNAME/gpteam/src/utils/database/seed.py", line 6, in <module>
    from src.utils.database.client import get_database
  File "/Users/USERNAME/gpteam/src/utils/database/client.py", line 5, in <module>
    from src.utils.database.sqlite import SqliteDatabase
  File "/Users/USERNAME/gpteam/src/utils/database/sqlite.py", line 9, in <module>
    from hyperdb import HyperDB
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/hyperdb/__init__.py", line 1, in <module>
    from .hyperdb import *
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/hyperdb/hyperdb.py", line 4, in <module>
    import openai
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/openai/__init__.py", line 19, in <module>
    from openai.api_resources import (
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/openai/api_resources/__init__.py", line 1, in <module>
    from openai.api_resources.audio import Audio  # noqa: F401
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/openai/api_resources/audio.py", line 4, in <module>
    from openai import api_requestor, util
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/openai/api_requestor.py", line 22, in <module>
    import requests
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/USERNAME/gpteam/venv/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
Traceback (most recent call last):
  File "/Users/USERNAME/gpteam/setup.py", line 66, in <module>
    subprocess.run(["poetry", "run", "db-reset"], check=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry', 'run', 'db-reset']' returned non-zero exit status 1.

```

**Comment by philip-pentatonic** [comment]
This error suggests that the version of OpenSSL installed on your system is incompatible with the urllib3 package version 2.0.

To resolve these issues, you can try the following steps:

Upgrade OpenSSL: Follow the instructions in the link provided in the error message (https://github.com/urllib3/urllib3/issues/2168) to upgrade OpenSSL to version 1.1.1 or higher. This should resolve the compatibility issue with urllib3.

Verify Poetry Installation: Confirm that Poetry is properly installed on your system. You can check the Poetry version by running `poetry --version` in your terminal. 

Check the setup.py file: Examine the setup.py file in your project and ensure that the command poetry run db-reset is correct and properly defined. If necessary, update the command or modify the script to handle the database reset differently.

Verify database configuration: Double-check your database configuration to ensure it is correctly set up and accessible. Ensure that the necessary database service is running.

Rebuild the virtual environment: If the above steps do not resolve the issue, you can try rebuilding the virtual environment from scratch. Delete the existing venv directory and recreate it using `python3 -m venv venv`. Then activate the virtual environment using `source venv/bin/activate` and reinstall the project dependencies.

btw - I'm a very basic coder and have found that if I just copy/paste error messages from the terminal in ChatGPT - it's great at giving clues and code to try to debug and fix. It's what i just did above with your error message :)

**Comment by walter-grace** [comment]
Installing the current project: 101-ai (0.1.0)
Seed the database...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/nicozahniser/Downloads/GPTeam-main/src/utils/database/reset.py", line 8, in <module>
    from .seed import seed
  File "/Users/nicozahniser/Downloads/GPTeam-main/src/utils/database/seed.py", line 6, in <module>
    from src.utils.database.client import get_database
  File "/Users/nicozahniser/Downloads/GPTeam-main/src/utils/database/client.py", line 5, in <module>
    from src.utils.database.sqlite import SqliteDatabase
  File "/Users/nicozahniser/Downloads/GPTeam-main/src/utils/database/sqlite.py", line 33, in <module>
    class SqliteDatabase(DatabaseProviderSingleton):
  File "/Users/nicozahniser/Downloads/GPTeam-main/src/utils/database/sqlite.py", line 121, in SqliteDatabase
    self, table: Tables, data: dict | list[dict], upsert=False
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'
Traceback (most recent call last):
  File "/Users/nicozahniser/Downloads/GPTeam-main/setup.py", line 66, in <module>
    subprocess.run(["poetry", "run", "db-reset"], check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry', 'run', 'db-reset']' returned non-zero exit status 1.

I am getting this error seems to be similar, I tried to activate the environment like above and still couldnt clear the error

**Comment by walter-grace** [comment]
Add Poetry to your PATH

The installer creates a poetry wrapper in a well-known, platform-specific directory:

$HOME/.local/bin on Unix.
%APPDATA%\Python\Scripts on Windows.
$POETRY_HOME/bin if $POETRY_HOME is set.
