### ISSUE TITLE
'LLMSinglePlan' object has no attribute 'related_message'

### ISSUE THREAD

**Issue by ilmonati** [101dotxyz/GPTeam#59]
I ran into this error:
```
[Rebecca] Act Starting to act on plan.
[Marty] Act Starting to act on plan.
[Ricardo] Observe Observed 0 new events since 22:43:22
[Rebecca] Observe Observed 1 new events since 22:43:12
[Marty] Observe Observed 0 new events since 22:43:25
Traceback (most recent call last):
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/main.py", line 46, in run_world_async
    await world.run()
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/world/base.py", line 113, in run
    await asyncio.gather(*tasks)
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/world/base.py", line 101, in run_agent_loop
    await self.run_next_agent()
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/world/base.py", line 96, in run_next_agent
    await agent.run_for_one_step()
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/agent/base.py", line 1075, in run_for_one_step
    await self._do_first_plan()
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/agent/base.py", line 976, in _do_first_plan
    await self._act(current_plan)
  File "/usr/local/google/home/ilmo/Downloads/GPTeam/src/agent/base.py", line 874, in _act
    if (plan.related_message):
AttributeError: 'LLMSinglePlan' object has no attribute 'related_message'
```

I believe changing `src/agent/base.py` (at line 873) will fix it:

```
        # Observe and react to new events
        await self.observe()

        # Gather relevant memories
        try:
            memory_query = plan.related_message.get_event_message()
        except AttributeError:
            memory_query = plan.description
        	
        relevant_memories = await get_relevant_memories(
            memory_query,
            memories=self.memories,
            k=20,
        )
```

**Comment by ilmonati** [comment]
Actually, if `related_message` gets set to None, same errors pop up elsewhere (e.g., line 888). It's probably worth solving the issue more robustly here (line 189):
```
            related_message = (
                AgentMessage.from_event(related_event, context)
                if related_event
                else None
            )
```
Could a string be used instead of None?

**Comment by ducatirob777** [comment]
I have experienced the same issue as @ilmonati

**Comment by mgunnin** [comment]
Ok I believe this should fix it.. Will submit a PR today.

Add the following line to 'src/agent/plans.py' on line 122.

`index: int = Field(description="The plan number")
    related_message: Optional[AgentMessage] = None`

**Comment by walter-grace** [comment]
[Rebecca] Moved Location Conference Room -> Park @ 20:34:52
Traceback (most recent call last):
  File "/Users/waltgrace/Downloads/GPTeam-main 2/.venv/lib/python3.11/site-packages/langchain/output_parsers/pydantic.py", line 25, in parse
    json_object = json.loads(json_str)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/waltgrace/Downloads/GPTeam-main 2/src/main.py", line 46, in run_world_async
    await world.run()
  File "/Users/waltgrace/Downloads/GPTeam-main 2/src/world/base.py", line 113, in run
    await asyncio.gather(*tasks)
  File "/Users/waltgrace/Downloads/GPTeam-main 2/src/world/base.py", line 101, in run_agent_loop
    await self.run_next_agent()
  File "/Users/waltgrace/Downloads/GPTeam-main 2/src/world/base.py", line 96, in run_next_agent
    await agent.run_for_one_step()
  File "/Users/waltgrace/Downloads/GPTeam-main 2/src/agent/base.py", line 1061, in run_for_one_step
    self.react_response = await self._react(events)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/waltgrace/Downloads/GPTeam-main 2/src/agent/base.py", line 846, in _react
    parsed_reaction_response: LLMReactionResponse = reaction_parser.parse(response)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/waltgrace/Downloads/GPTeam-main 2/.venv/lib/python3.11/site-packages/langchain/output_parsers/fix.py", line 38, in parse
    parsed_completion = self.parser.parse(new_completion)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/waltgrace/Downloads/GPTeam-main 2/.venv/lib/python3.11/site-packages/langchain/output_parsers/pydantic.py", line 31, in parse
    raise OutputParserException(msg)
langchain.schema.OutputParserException: Failed to parse LLMReactionResponse from completion Decision: continue

Thought process: "I should continue with my current plan because I haven't received any new information or messages that require my immediate attention. I will continue to be cautious and avoid getting caught by the authorities. I will keep my eyes and ears open for any potential deals or opportunities that come my way.". Got: Expecting value: line 1 column 1 (char 0)

Same error... Does this code not work anymore?

**Comment by MoHayat** [comment]
There does seem to be a decoding issue if you let it run for long enough, might be a missing handler for a specific response from OpenAI

**Comment by Alec2435** [comment]
This usually happens because `gpt-3.5-turbo` generates a bad output and whichever area this is coming from doesn't have sufficient retry logic. When running with gpt-4 this should be much more infrequent, although quite costly.
