### ISSUE TITLE
setup.py fails when run inside a conda env

### ISSUE THREAD

**Issue by MoHayat** [101dotxyz/GPTeam#65]
I set up a conda env running python 3.9 to work on GPTeam, once I activated it and ran the setup command I received the following error. The setup command worked normally after I deactivated the env, but it might be better to have it hosted in an environment to isolate it from any other dependencies I have locally.

```TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'
Traceback (most recent call last):
  File "/Users/mohayat/projects/GPTeam/setup.py", line 66, in <module>
    subprocess.run(["poetry", "run", "db-reset"], check=True)
  File "/Users/mohayat/anaconda3/envs/gpteam/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry', 'run', 'db-reset']' returned non-zero exit status 1.```

**Comment by MoHayat** [comment]
@jjhesk your rec worked! appreciate the help.
