### ISSUE TITLE
How do you even use this?

### ISSUE THREAD

**Issue by cranyy** [101dotxyz/GPTeam#66]
How do i setup the agents properly, what are these locations, and what the heck is this improv thing? I know i am new, but can you please give a more detailed explanation on how to actually setup the agents with different prompts/roles? Do i have to edit the config file directly and rewrite it every time?

**Comment by cranyy** [comment]
and i get this error when I run it for a little bit with my own prompts painstakingly hard coded into the config:

raceback (most recent call last):
  File "C:\Users\marin\GPTeam\src\main.py", line 46, in run_world_async
    await world.run()
  File "C:\Users\marin\GPTeam\src\world\base.py", line 113, in run
    await asyncio.gather(*tasks)
  File "C:\Users\marin\GPTeam\src\world\base.py", line 101, in run_agent_loop
    await self.run_next_agent()
  File "C:\Users\marin\GPTeam\src\world\base.py", line 96, in run_next_agent
    await agent.run_for_one_step()
  File "C:\Users\marin\GPTeam\src\agent\base.py", line 1072, in run_for_one_step
    await self._do_first_plan()
  File "C:\Users\marin\GPTeam\src\agent\base.py", line 973, in _do_first_plan
    await self._act(current_plan)
  File "C:\Users\marin\GPTeam\src\agent\base.py", line 876, in _act
    if plan.related_message
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LLMSinglePlan' object has no attribute 'related_message'

Exception ignored in: <coroutine object ChatOpenAI._agenerate at 0x000001C035763810>
Traceback (most recent call last):
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\langchain\chat_models\openai.py", line 318, in _agenerate
    response = await acompletion_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\langchain\chat_models\openai.py", line 63, in acompletion_with_retry
    return await _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\marin\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\langchain\chat_models\openai.py", line 61, in _completion_with_retry
    return await llm.client.acreate(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object ChatOpenAI._agenerate at 0x000001C035762D60>
Traceback (most recent call last):
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\langchain\chat_models\openai.py", line 318, in _agenerate
    response = await acompletion_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\langchain\chat_models\openai.py", line 63, in acompletion_with_retry
    return await _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\marin\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\langchain\chat_models\openai.py", line 61, in _completion_with_retry
    return await llm.client.acreate(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marin\GPTeam\env\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit

**Comment by MoHayat** [comment]
hey @cranyy, there are a few solutions you could try in [this issue](https://github.com/101dotxyz/GPTeam/issues/59) for that problem you came across.
