### ISSUE TITLE
LLMSinglePlan object has no attribute "related_messages"

### ISSUE THREAD

**Issue by MoHayat** [101dotxyz/GPTeam#70]
I've spun up my world using `poetry run world --turbo` and after letting the world run for a while all agents seem to stop and I get this error message: 
```
Traceback (most recent call last):
  File "/Users/mohayat/projects/GPTeam/src/main.py", line 46, in run_world_async
    await world.run()
  File "/Users/mohayat/projects/GPTeam/src/world/base.py", line 113, in run
    await asyncio.gather(*tasks)
  File "/Users/mohayat/projects/GPTeam/src/world/base.py", line 101, in run_agent_loop
    await self.run_next_agent()
  File "/Users/mohayat/projects/GPTeam/src/world/base.py", line 96, in run_next_agent
    await agent.run_for_one_step()
  File "/Users/mohayat/projects/GPTeam/src/agent/base.py", line 1072, in run_for_one_step
    await self._do_first_plan()
  File "/Users/mohayat/projects/GPTeam/src/agent/base.py", line 973, in _do_first_plan
    await self._act(current_plan)
  File "/Users/mohayat/projects/GPTeam/src/agent/base.py", line 876, in _act
    if plan.related_message
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LLMSinglePlan' object has no attribute 'related_message'
```

I've tried making my changes locally but it keeps running into the same issue. Any advice?

**Comment by MoHayat** [comment]
this may be related to [Issue #59](https://github.com/101dotxyz/GPTeam/issues/59), trying the solution mentioned in that thread.

**Comment by walter-grace** [comment]
Getting the same error, it seems to be when it wants to generate text

**Comment by MoHayat** [comment]
[this fix](https://github.com/101dotxyz/GPTeam/issues/59#issuecomment-1559533289) got rid of the error on my end, but I still run into the encoding errors you mentioned in the other thread, trying to get to the bottom of that.
